#!/bin/bash
diff MultiN.fastq corrupted.fastq

#The differences were at lines 93-94 and 1421 - 1424

#93,94c93
#< @M00618:17:000000000-A31W7:1:1101:13859:2209 1:N:0:21
#< GGAGGCGAGAGCGGAGACGACGGTGATCTGGGAGATCGACGAGGGGCAGAAGCGCATCGAGGGCNNNNACGAGGCCGGTCGCCCCGACCCCGCCTACGCGGCCGCGCTCGGGCTCCGCCCCGCGCCGCTCGGCCGTCGCGCGCTCGCGTCGATCATCGAGCTCTCGCTCTACGCGCTGCTGCAGCTGCCGTACTGGCTCGTCGCCCTGCCCTCGCTCGTGCGGATCGCGACCGCACGCTCCGTCATGCGCG
#---
#> TGATCTGGGAGATCGACGAGGGGCAGAAGCGCATCGAGGGCNNNNACGAGGCCGGTCGCCCCGACCCCGCCTACGCGGCCGCGCTCGGGCTCCGCCCCGCGCCGCTCGGCCGTCGCGCGCTCGCGTCGATCATCGAGCTCTCGCTCTACGCGCTGCTGCAGCTGCCGTACTGGCTCGTCGCCCTGCCCTCGCTCGTGCGGATCGCGACCGCACGCTCCGTCATGCGCG
#1421,1424c1420
#< @M00618:17:000000000-A31W7:1:1101:15910:4449 1:N:0:21
#< CACGAGGCGGTGCGCGAGCGCCGGCACGGCGAGCGCCTTGACGTCGTCGGGGGTCACGTAGTCGCGGCCGTGGATCGCTGCCCACGCGCGCGCCGTCCGCACGAGCGCGAGCGCGCCGCGCACCGAGACGCCCAGGCGCACCTCGTCGGCCTCGCGCGTCGCGTCGACGAGCCGCGCGACGTAGTCGACGATCGACGCCTCGACGTGGACGCCGCGCACCTGGTCCGCGAGCGGGCCGGACGGCCATGTGC
#< +
#< AAAAAAAADEDDDDDDGGGGGGHHHHHHHHHHHHHHHHGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGGGGGGGECEEDGGDGGGGGGDA>GGEGDGGD<DGGGGGGGGDGGDAD>AGGGG<8?CC?8.4<>E.<C8>'.9CEGA84?88*''5'.'..'8:*****...5'4.'''''''''''''*****
#---
#> AAADEDDDDDDGGGGGGHHHHHHHHHHHHHHHHGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGGGGGGGECEEDGGDGGGGGGDA>GGEGDGGD<DGGGGGGGGDGGDAD>AGGGG<8?CC?8.4<>E.<C8>'.9CEGA84?88*''5'.'..'8:*****...5'4.'''''''''''''*****

